### ISSUE TITLE
TypeError: Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by juanpasolano** [sapegin/bower-update#9]
I am getting this error when updating
```
/usr/local/lib/node_modules/bower-update/node_modules/bower/node_modules/q/q.js:126
                    throw e;
                          ^
TypeError: Cannot read property 'update' of undefined
    at /usr/local/lib/node_modules/bower-update/index.js:46:36
    at /usr/local/lib/node_modules/bower-update/node_modules/lodash/dist/lodash.js:3513:29
    at forOwn (/usr/local/lib/node_modules/bower-update/node_modules/lodash/dist/lodash.js:2105:15)
    at Function.map (/usr/local/lib/node_modules/bower-update/node_modules/lodash/dist/lodash.js:3512:9)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower-update/index.js:41:19)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower-update/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower-update/node_modules/bower/lib/commands/index.js:38:25
    at _fulfilled (/usr/local/lib/node_modules/bower-update/node_modules/bower/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/bower-update/node_modules/bower/node_modules/q/q.js:816:30)
```

**Comment by ysfjwd** [comment]
:+1:

**Comment by adamayres** [comment]
+1

**Comment by atgillette** [comment]
+1

**Comment by kezugo** [comment]
+1 node 0.12

**Comment by amercier** [comment]
+1

**Comment by sapegin** [comment]
Should be fixed now. Sorry for the delay.
